---
title: "Climate Summaries of USA_BGC"
author: "William H MacKenzie"
date: "29/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in the hexgrid climate data with predicted subzone 

```{r read in hexgrid w climate data}
grid.dat.pred <- fread("./outputs/Hexgrid800mPredictedtoSubZone_30vars.csv")
grid.dat.pred <- grid.dat.pred %>%  select(ID1, Zone, everything()) %>% rename(BGC = Zone)
grid.dat.pred$BGC <- as.factor(grid.dat.pred$BGC )
```

## Extract a training point set for climate summaries
select a subset of training points by BGC from the final surface for full model build

```{r cLHS of trainingpoints for WNA}

library(clhs)
#BGC = "ICHxwz"
#countZone <- points %>% count(Zone)
countSubzone <- grid.dat.pred %>% count(BGC)

rownames(grid.dat.pred) <- grid.dat.pred[,1]
countSubzone$logn <- log(countSubzone$n, 10)
countSubzone$rs <- as.integer (rescale(countSubzone$logn, to = c(500, 1200), from = range(countSubzone$logn, na.rm = TRUE, finite = TRUE)))
countSubzone$sample <- ifelse(countSubzone$rs > countSubzone$n, countSubzone$n, countSubzone$rs )
write.csv (countSubzone, "./outputs/USA_pts_per_BECLHC2.csv")

allUnits <- unique(grid.dat.pred$BGC))
#grid.dat.pred$ID1 <- row.names(grid.dat.pred)
set.seed(123321)
coreNo <- makePSOCKcluster(detectCores() - 1)
registerDoParallel(coreNo, cores = detectCores() - 1)
Cores <- as.numeric(detectCores()-1)

BGC = "CCHun_CA"
LHCtraining <- foreach(BGC = allUnits, .combine = rbind, .packages = c("clhs")) %dopar% {
temp <- grid.dat.pred[(grid.dat.pred$BGC %in% BGC),]
temp_names <- temp[1:6]
Num <- countSubzone$sample[(countSubzone$BGC %in% BGC)]
  samples <- clhs(temp[,-c(1:6)],
                size = Num,           # Test a range of sample sizes
                iter = 100,        # Arbitrarily large number of iterations of optimization procedure. Default=10,000 but a larger number may be used
                progress = TRUE,
                simple = FALSE)

cLHS <- samples$sampled_data
cLHS$ID1 <- row.names (cLHS)
cLHS_Points <- merge (temp[,c(1:5)], cLHS, by = "ID1")
cLHS_Points
}
 stopCluster(coreNo)
 gc()

write.csv(LHCtraining, "./outputs/USA_Training_LHC_w_data.csv", row.names = FALSE)
LHCtraining2 <- LHCtraining [1:3]
rownames(grid.dat.raw) <- grid.dat.raw[,1]
LHCtraining2 <- left_join(LHCtraining2, grid.dat.raw, by = "ID1")
write.csv(LHCtraining2, "./outputs/USA_LHS_all_dat.csv", row.names = FALSE)
USA_LHS <- dplyr::select(LHCtraining2, ID1, BGC, Longitude, Latitude, Elevation)
write.csv(USA_LHS, "./outputs/USA_LHS_for_ClimateNA.csv", row.names = FALSE)
X1 <- LHCtraining #feed these back into building a new rF model above
```
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
